---
- name: Add master/bastion to created_vms group
  add_host:
    name={{ item.ip }}
    groups=created_vms
    instance_name={{ item.name }}
  with_items:
    - { name: 'master', ip: '{{master_public_ip}}' }
    - { name: 'bastion', ip: '{{bastion_public_ip}}' }  

- name: Add nodes to created_vms group
  add_host:
    name={{ item.public_ip }}
    groups=created_vms
    instance_name=node{{ item.index }}
  with_items: "{{ nodes_ip }}"

- name: Add master to created_nodes group
  add_host:
    name={{ item.ip }}
    groups=created_nodes
    instance_name={{ item.name }}
  with_items:
    - { name: 'master', ip: '{{master_public_ip}}' }

- name: Add nodes to created_nodes group
  add_host:
    name={{ item.public_ip }}
    groups=created_nodes
    instance_name=node{{ item.index }}
  with_items: "{{ nodes_ip }}"

- name: Master host
  add_host:
    name={{ master_public_ip}}
    groups=master
    instance_name=master

- name: Bastion host
  add_host:
    name={{ bastion_public_ip}}
    groups=bastion
    instance_name=bastion