---
#############################################################
# Provision AWS infrastructure
#############################################################
- name: Create Infrastructure
  hosts: local

  vars_files:
    - vars/aws-config.yml

  roles:
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh
  - setup-host-groups

  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that: 
          - "ansible_version.major == 2"
          - "ansible_version.minor >= 4"
        msg: "This script is only supported with the 2.4.1 version or later of Ansible"
    
    - fail: msg="Variables required to register subscriptions are missing, please confirm that either rhsm_username, rhsm_password and rhsm_pool OR rhsm_key_id and rhsm_org_id is defined"
      when: (deployment_type == 'openshift-enterprise') and not (((rhsm_username is defined) and (rhsm_password is defined) and (rhsm_pool is defined)) or ((rhsm_key_id is defined) and (rhsm_org_id is defined)))

#############################################################
# Register and update virtual machines
#############################################################
- name: Setup VM hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

- name: Register and update virtual machines
  hosts: created_vms
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:    

  - {role: register-virtual-machines, when: deployment_type == 'openshift-enterprise'}
  - update-virtual-machines

#############################################################
# Generate SSL certificates using lets encrypt, fetch to
# local system and then set ssl vars
#############################################################
- name: Generate SSL certificates
  hosts: master
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  roles:    

  - {role: generate-ssl-certs, when: use_lets_encrypt}

#############################################################
# Copy SSL certificates to bastion
#############################################################
- name: Copy SSL certificates to bastion
  hosts: bastion
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  tasks:
    - name: Set master SSL facts for lets encrypt
      set_fact:
        master_ssl_cert_file: certs/letsencrypt/{{public_dns_zone}}/fullchain.pem
        master_ssl_key_file: certs/letsencrypt/{{public_dns_zone}}/privkey.pem
      when: use_lets_encrypt

    - name: create directory for certs
      file: path=certs/{{public_dns_zone}} state=directory

    - name: copy master SSL certificates to bastion
      copy:
        src: "{{item}}"
        dest: certs/{{public_dns_zone}}/{{item | basename}}
      with_items:
        - "{{master_ssl_cert_file}}"
        - "{{master_ssl_key_file}}"
      when: master_ssl_cert_file is defined

#############################################################
# Openshift Prerequisites
#############################################################
- name: Setup Node hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

- name: OpenShift Prerequisites
  hosts: created_nodes
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:
  - openshift-pre-reqs

#############################################################
# Install Openshift
#############################################################
- name: Install OpenShift
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

  vars:
#    nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'

  pre_tasks:
  - name: Set master SSL facts for lets encrypt
    set_fact:
      master_ssl_cert_file: certs/letsencrypt/{{public_dns_zone}}/fullchain.pem
      master_ssl_key_file: certs/letsencrypt/{{public_dns_zone}}/privkey.pem
    when: use_lets_encrypt

  roles:
  - openshift-install

#############################################################
# Post-install tasks 
#############################################################
- name: Post-Install tasks 
  hosts: master
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  pre_tasks:
  - name: Set master SSL facts for lets encrypt
    set_fact:
      master_ssl_cert_file: certs/letsencrypt/{{public_dns_zone}}/fullchain.pem
      master_ssl_key_file: certs/letsencrypt/{{public_dns_zone}}/privkey.pem
    when: use_lets_encrypt

  - name: Set wildcard SSL facts
    set_fact:
      wildcard_ssl_cert_file: certs/letsencrypt/{{public_subdomain_prefix}}.{{public_dns_zone}}/fullchain.pem
      wildcard_ssl_key_file: certs/letsencrypt/{{public_subdomain_prefix}}.{{public_dns_zone}}/privkey.pem
    when: use_lets_encrypt

  post_tasks:
   - name: SSL certificate information
     debug:
       msg: 
         - 'SSL certificates have been generated using letsencrypt and backed up locally:'
         - '\tcerts/letsencrypt\n'
         - 'Note that letsencrypt is rate limited to 20 requests a week and SSL certificates last for 90 days.'
         - 'If you need to run the playbook again, consider using the certificates backed up locally by'
         - 'setting the following variables in vars/aws_config.yml'
         - '\tmaster_ssl_cert_file: "{{master_ssl_cert_file}}"'
         - '\tmaster_ssl_key_file: "{{master_ssl_key_file}}"'
         - '\wildcard_ssl_cert_file: "{{wildcard_ssl_cert_file}}"'
         - '\twildcard_ssl_key_file: "{{wildcard_ssl_key_file}}"'
     when: use_lets_encrypt

  roles:
  - add-users
  - {role: openshift-gluster-sc, when: install_gluster}
  - {role: update-ssl-cockpit, when: master_ssl_cert_file is defined}
  - {role: update-ssl-router, when: wildcard_ssl_cert_file is defined}
  - {role: disable-service-catalog, when: disable_service_catalog}

#############################################################
# Output environment information
#############################################################
- name: OpenShift Information
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

  tasks:
   - name: Confirmation message
     debug:
      msg: 
        - 'The script has completed successfully.'
        - 'Master public IP: {{master_public_ip}}'
        - 'OpenShift console: https://{{public_dns_zone}}:8443'