#####################################################################
# Variables you should update for your installation
#####################################################################

# AWS region to install environment into
region: "us-west-2"

# The public DNS for cluster, you must have a Route 53 zone configured for this
public_dns_zone: "ocplab.com"
# Prefix for subdomain for wildcard DNS, i.e. *.apps.ocplab.com
public_subdomain_prefix: "apps"

# Amazon key pair to use, must exist before running script. Please generate in AWS management console.
aws_key_pair: "mykeypair"

# You have a choice, if you know the specific AMI you want to use, reference it by ami_id
# If you do not know the ami_id, comment out the ami_id variable and uncomment the redhat_owner_id

# Use the owner tag if you want to look up the AMI automatically
#redhat_owner_id: "309956199498"

# Use ami_id if you know the specific ami you want to use, note the ami
# below refers to a gold image in us-west-2, it's unlikely you have access
# to it so change this variable to something appropriate. Use the AWS console
# to locate a suitable image
ami_id: "ami-cfa343b7"

# Whether to install metrics
install_metrics: false
# Whether to install prometheus
install_prometheus: false
# Whether to install logging
install_logging: false

# Users to create in OpenShift, highly recommend changing password
# Set admin to true for users you want to be the cluster administrator
# Any admin users are also added to master linux VM for cockpit
users:
  - {name: admin, password: changeme!, admin: true}

# Generates a set of non-admin users that can be used for workshops,
# demos, etc. Users are created with the prefix plus a number using
# the password specified
create_generic_user: true
generic_user_prefix: developer
generic_user_count: 5
generic_user_password: changeme!

#####################################################################
# SSL configuration - Optional
#####################################################################

# Option 1: Install SSL certificates for the master that you provide or
# were previously generated by Option 2
# master_ssl_cert_file: "certs/letsencrypt/ocplab.com/fullchain.pem"
# master_ssl_key_file: "certs/letsencrypt/ocplab.com/privkey.pem"

# Note only the cert file, not full chain
# hawkular_ssl_cert_file: "certs/letsencrypt/hawkular-metrics.apps.ocplab.com/cert.pem"
# hawkular_ssl_chain_file: "certs/letsencrypt/hawkular-metrics.apps.ocplab.com/chain.pem"
# hawkular_ssl_key_file: "certs/letsencrypt/hawkular-metrics.apps.ocplab.com/privkey.pem"

# Option 2: Use let's encrypt to generate certs for master and hawkular
# note certs will be fetched to location where script is run to back
# them up and possible re-use
use_lets_encrypt: false
# e-mail address that owns the certs generated by letsencrypt
domain_email_address: "me@me.com"

#####################################################################
# Variables you may optionally change for your installation
#####################################################################

# Variables for node configuration
bastion_ami_size: "t2.small"
master_ami_size: "m4.xlarge"
node_ami_size: "t2.large"
master_root_volume_size: 50
node_root_volume_size: 30
docker_volume_size: 50

# The number of application nodes in the cluster
app_nodes: 3

# The type of OpenShift deployment, must be either origin or openshift-enterprise.
# To install OpenShift Enterprise, you must have a valid OpenShift subscription
# with Red Hat and provide your subscription login and pool
deployment_type: "openshift-enterprise"

# Only needed for Origin
# openshift_branch: "release-3.6"ocplab.com

# Only needed for Container Platform
ocp_version: "3.7"

# If true, openshift will be installed with a default node selector set to region=primary
# to prevent applications from running on the master
install_node_selector: true

#####################################################################
# This playbook can optionally install CNS (Gluster) for applications. It
# requires three nodes dedicated to it which will be provisioned by the
# playbook automatically. Note this installs gluster for
# apps use only, the registry will continue to use AWS storage.
#####################################################################
install_gluster: false
gluster_ami_size: m4.xlarge
# This volume size is per gluster node so total storage is (gluster_volume_size * 3)
gluster_volume_size: 100

#####################################################################
# Variables you do not want to change unless you are sure you know 
# what you are doing
#####################################################################

# namespace is used to uniquely differentiate the stack
namespace: "openshift"
# dns_zone is private zone, created and deleted by scripts
dns_zone: "ose.local"

vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"

amazon_user: "ec2-user"

# This must match what is in /openshift-install/files/openshift_inventory.cfg
htpasswd_path: "/etc/origin/master/htpasswd"

# epel repo url, needed for certbot and lets encrypt
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

# Used for SSL certificates for hawkular, do not change this
hawkular_domain: "hawkular-metrics.{{public_subdomain_prefix}}.{{public_dns_zone}}"

# If true, the service catalog will be disabled
disable_service_catalog: false